### ISSUE TITLE
module "LoadingAnimation" is not installed

### ISSUE THREAD

**Issue by semlanik** [zl0i/QtAutoTools#1]
When running app it's not possible to open any form, because of QML error:
module "LoadingAnimation" is not installed

**Comment by zl0i** [comment]
Hello, this is my mistake, you can download the deployment or installer of the project or download the module Loading Animation at this link https://github.com/zl0i/ModuleQML I will add this file to the project at the next commit.

**Comment by zl0i** [comment]
Hi, I added Loading Animation to the project. I think I can close the issues.
